-- MalaysiaGO quiz content. Apply with `supabase db push` or paste into the
-- Supabase SQL Editor. Coordinates are WGS84 points for the visitor-facing
-- landmark/gateway and are stored to six decimal places (well within 1 km).

create table if not exists public.quiz_sites (
  site_id text primary key,
  name text not null,
  icon text not null default '📍',
  location text not null,
  category text not null,
  description text not null,
  difficulty text not null default 'Easy',
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  updated_at timestamptz not null default now()
);

create table if not exists public.quiz_questions (
  id bigint generated by default as identity primary key,
  site_id text not null references public.quiz_sites(site_id) on delete cascade,
  display_order smallint not null check (display_order > 0),
  question text not null,
  options jsonb not null check (jsonb_typeof(options) = 'array' and jsonb_array_length(options) = 4),
  correct_index smallint not null check (correct_index between 0 and 3),
  explanation text not null,
  xp_reward smallint not null default 25 check (xp_reward > 0),
  is_active boolean not null default true,
  unique (site_id, display_order)
);

alter table public.quiz_sites enable row level security;
alter table public.quiz_questions enable row level security;

drop policy if exists "Public can read quiz sites" on public.quiz_sites;
create policy "Public can read quiz sites" on public.quiz_sites for select using (true);
drop policy if exists "Public can read active quiz questions" on public.quiz_questions;
create policy "Public can read active quiz questions" on public.quiz_questions for select using (is_active);

insert into public.quiz_sites (site_id, name, icon, location, category, description, difficulty, latitude, longitude) values
  ('batu_caves', 'Batu Caves', '⛩️', 'Selangor · Religious', 'Religious', 'Sacred limestone cathedral above Kuala Lumpur', 'Easy', 3.237934, 101.683984),
  ('merdeka_square', 'Dataran Merdeka', '🏳️', 'Kuala Lumpur · National', 'National', 'Historic square where Malaysia''s independence was declared in 1957', 'Easy', 3.147860, 101.693775),
  ('george_town', 'George Town', '🏛️', 'Penang · UNESCO', 'UNESCO', 'Historic colonial port city famous for street art and heritage shophouses', 'Medium', 5.414130, 100.328750),
  ('malacca_city', 'Malacca City', '🏯', 'Melaka · UNESCO', 'UNESCO', 'Historic trading port shaped by Portuguese, Dutch, and British rule', 'Medium', 2.189594, 102.250086),
  ('masjid_zahir', 'Zahir Mosque', '🕌', 'Kedah · Religious', 'Religious', 'One of Malaysia''s oldest and grandest mosques, completed in 1912', 'Easy', 6.121736, 100.367257),
  ('lenggong_valley', 'Lenggong Valley', '🏺', 'Perak · UNESCO', 'UNESCO', 'UNESCO-listed archaeological valley where Perak Man was discovered', 'Medium', 5.107540, 100.971580),
  ('crystal_mosque', 'Crystal Mosque', '🕌', 'Terengganu · Religious', 'Religious', 'A steel-and-glass mosque on an island in the Terengganu River', 'Easy', 5.322160, 103.120670),
  ('taman_negara', 'Taman Negara (Kuala Tahan)', '🌳', 'Pahang · Nature', 'Nature', 'Main visitor gateway to one of the world''s oldest rainforests', 'Medium', 4.381349, 102.401529),
  ('sultan_abu_bakar_mosque', 'Sultan Abu Bakar State Mosque', '🕌', 'Johor · Religious', 'Religious', 'A Victorian-Moorish mosque overlooking the Johor Strait', 'Medium', 1.465265, 103.757401)
on conflict (site_id) do update set
  name = excluded.name, icon = excluded.icon, location = excluded.location,
  category = excluded.category, description = excluded.description,
  difficulty = excluded.difficulty, latitude = excluded.latitude,
  longitude = excluded.longitude, updated_at = now();

insert into public.quiz_questions (site_id, display_order, question, options, correct_index, explanation, xp_reward) values
  ('batu_caves', 1, 'How many steps lead up to the Cathedral Cave at Batu Caves?', '["182 steps","272 steps","320 steps","214 steps"]', 1, 'The iconic staircase has 272 steps.', 27),
  ('batu_caves', 2, 'What is the height of the golden Lord Murugan statue at Batu Caves?', '["28 metres","35 metres","43 metres","55 metres"]', 2, 'The gold-plated statue is 43 metres high.', 27),
  ('batu_caves', 3, 'Which Hindu festival draws devotees to Batu Caves each year?', '["Thaipusam","Deepavali","Vesak Day","Ponggal"]', 0, 'Thaipusam is the site''s major annual festival.', 26),
  ('merdeka_square', 1, 'What happened at Dataran Merdeka on 31 August 1957?', '["Independence was declared","A king was crowned","The railway opened","A peace treaty was signed"]', 0, 'The Malayan flag was raised as independence was declared.', 27),
  ('merdeka_square', 2, 'What was the square historically used for?', '["A cricket field","A horse track","A market","A military base"]', 0, 'It was the Selangor Club Padang.', 27),
  ('merdeka_square', 3, 'About how tall is its flagpole?', '["95 metres","20 metres","50 metres","150 metres"]', 0, 'The flagpole is about 95 metres tall.', 26),
  ('george_town', 1, 'When were George Town and Malacca jointly inscribed by UNESCO?', '["2000","2008","2012","2015"]', 1, 'The historic cities were inscribed in 2008.', 27),
  ('george_town', 2, 'Which public art form is George Town famous for?', '["Street murals","Sand sculpture","Ice sculpture","Neon art"]', 0, 'Interactive street murals are a signature of the historic core.', 27),
  ('george_town', 3, 'Who founded George Town in 1786?', '["Francis Light","Stamford Raffles","James Brooke","Alfonso de Albuquerque"]', 0, 'Francis Light founded the settlement for the British East India Company.', 26),
  ('malacca_city', 1, 'Which European power first colonised Malacca in 1511?', '["Portuguese","Dutch","British","Spanish"]', 0, 'Portuguese forces captured Malacca in 1511.', 27),
  ('malacca_city', 2, 'What is the name of the Portuguese fortress ruins?', '["A Famosa","Fort Cornwallis","Fort Santiago","Fort Margherita"]', 0, 'The surviving gate is Porta de Santiago of A Famosa.', 27),
  ('malacca_city', 3, 'Which strategic strait does Malacca sit beside?', '["Strait of Malacca","Strait of Hormuz","Bosphorus","Strait of Gibraltar"]', 0, 'Its position on the Strait of Malacca made it a major trading port.', 26),
  ('masjid_zahir', 1, 'In what year was Zahir Mosque completed?', '["1887","1912","1935","1957"]', 1, 'Zahir Mosque was completed in 1912.', 30),
  ('masjid_zahir', 2, 'Zahir Mosque is in which Kedah city?', '["Alor Setar","Sungai Petani","Kulim","Langkawi Town"]', 0, 'It stands in Alor Setar, Kedah''s capital.', 30),
  ('masjid_zahir', 3, 'Its five domes are said to represent what?', '["Five Pillars of Islam","Five states","Five founders","Five prayers only"]', 0, 'They are commonly said to symbolise the Five Pillars.', 30),
  ('lenggong_valley', 1, 'When was Lenggong Valley inscribed as a UNESCO World Heritage Site?', '["2000","2008","2012","2019"]', 2, 'Lenggong Valley was inscribed in 2012.', 40),
  ('lenggong_valley', 2, 'About how old is Perak Man?', '["5,000 years","8,000 years","11,000 years","20,000 years"]', 2, 'Perak Man is estimated to be around 11,000 years old.', 40),
  ('lenggong_valley', 3, 'Where was Perak Man discovered?', '["A limestone cave","A rice field","A temple","A shell midden"]', 0, 'The skeleton was found at Gua Gunung Runtuh.', 40),
  ('crystal_mosque', 1, 'In what year did the Crystal Mosque open?', '["1998","2003","2008","2015"]', 2, 'It opened in 2008.', 30),
  ('crystal_mosque', 2, 'Which materials give the Crystal Mosque its name?', '["Steel and glass","Marble and gold","Bamboo and thatch","Granite and copper"]', 0, 'Its reflective steel-and-glass structure inspires the name.', 30),
  ('crystal_mosque', 3, 'On which river island does it stand?', '["Wan Man Island in the Terengganu River","Penang Island","Langkawi Island","Redang Island"]', 0, 'It is on Wan Man Island in the Terengganu River.', 30),
  ('taman_negara', 1, 'Taman Negara is estimated to be roughly how old?', '["10 million years","50 million years","130 million years","500 million years"]', 2, 'Its rainforest is commonly estimated at about 130 million years old.', 37),
  ('taman_negara', 2, 'Which village is the usual gateway for park treks?', '["Kuala Tahan","Kuala Besut","Kuala Kubu Bharu","Kuala Lipis"]', 0, 'Kuala Tahan is the principal visitor gateway.', 37),
  ('taman_negara', 3, 'Which three states does the park span?', '["Pahang, Kelantan, Terengganu","Selangor, Perak, Kedah","Johor, Melaka, Negeri Sembilan","Sabah, Sarawak, Labuan"]', 0, 'The national park crosses Pahang, Kelantan, and Terengganu.', 36),
  ('sultan_abu_bakar_mosque', 1, 'Who is the Sultan Abu Bakar State Mosque named after?', '["Sultan Abu Bakar","Sultan Ibrahim","Sultan Iskandar","Sultan Mahmud Shah"]', 0, 'It honours the ruler credited with modernising Johor.', 30),
  ('sultan_abu_bakar_mosque', 2, 'Which strait does the mosque overlook?', '["Johor Strait","Strait of Malacca","Penang Strait","Karimata Strait"]', 0, 'The mosque has views toward Singapore across the Johor Strait.', 30),
  ('sultan_abu_bakar_mosque', 3, 'The mosque blends Islamic design with which influence?', '["Victorian British","Japanese","Spanish colonial","Scandinavian"]', 0, 'Its architecture combines Moorish Islamic and Victorian British elements.', 30)
on conflict (site_id, display_order) do update set
  question = excluded.question, options = excluded.options, correct_index = excluded.correct_index,
  explanation = excluded.explanation, xp_reward = excluded.xp_reward, is_active = true;


